apiVersion: v1
kind: Pod
metadata:
  name: cilium-network-debugger
  namespace: kube-system
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: debugger
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
        - SYS_PTRACE
    volumeMounts:
    - name: host-root
      mountPath: /host
      readOnly: false
    - name: cni
      mountPath: /etc/cni/net.d
    - name: var-run-cilium
      mountPath: /var/run/cilium
    - name: sys
      mountPath: /sys
  volumes:
  - name: host-root
    hostPath:
      path: /
  - name: cni
    hostPath:
      path: /etc/cni/net.d
  - name: var-run-cilium
    hostPath:
      path: /var/run/cilium
  - name: sys
    hostPath:
      path: /sys
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/os: linux
